name: 'Setup Pub'
description: 'Setup the Dart Pub cache for the workflow'

runs:
  using: composite
  steps:
    # https://github.com/marketplace/actions/cache
    - name: Cache Pub dependencies
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      env:
        cache-name: pub
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-

    - name: Path pub-cache
      shell: bash
      run: echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"

    - name: Setup workspaces
      shell: bash
      run: |
        dart pub global activate melos
        dart pub get --enforce-lockfile
        melos bootstrap:post_hooks
