name: 'Setup Pub'
description: 'Setup the Dart Pub cache for the workflow'

inputs:
  skip-linking:
    description: 'melos bootstrap skip linking'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    # https://github.com/marketplace/actions/cache
    - name: cache pub
      id: cache
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      env:
        cache-name: pub
      with:
        # pub-cache files are stored in `~/.pub-cache` on Linux/macOS
        path: ~/.pub-cache
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
          ${{ runner.os }}-${{ env.cache-name }}-
          ${{ runner.os }}-

    - name: Path pub-cache
      shell: bash
      run: echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"

    - name: Setup Melos
      shell: bash
      run: |
        dart pub global activate melos
        
        if [ "${{ inputs.skip-linking }}" == "true" ]; then
          melos bootstrap --skip-linking
        else
          melos bootstrap
        fi
