version: 2
enable-beta-ecosystems: true
updates:
  # GitHub Actions の依存関係を管理
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "ignore for release"
    open-pull-requests-limit: 10

  # npm / bun の依存関係を管理
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      bun-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  # Dart / Flutter の依存関係を管理（ワークスペース全体）
  - package-ecosystem: "pub"
    directories:
      - "/"
      - "/app/backend"
      - "/app/catalog"
      - "/app/mobile"
      - "/core/analytics"
      - "/core/analytics_firebase"
      - "/core/authenticator"
      - "/core/common"
      - "/core/data"
      - "/core/database"
      - "/core/database_isar"
      - "/core/datastore"
      - "/core/designsystem"
      - "/core/domain"
      - "/core/model"
      - "/core/network"
      - "/core/network_model"
      - "/core/testing"
      - "/core/ui"
      - "/feature/auth"
      - "/feature/debug"
      - "/feature/feed"
      - "/feature/home"
      - "/feature/onboarding"
      - "/feature/quest"
      - "/feature/settings"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      envied:
        patterns:
          - "envied"
          - "envied_generator"
      riverpod:
        patterns:
          - "flutter_riverpod"
          - "hooks_riverpod"
          - "riverpod"
          - "riverpod_*"
      isar:
        patterns:
          - "isar"
          - "isar_flutter_libs"
      firebase:
        patterns:
          - "cloud_firestore"
          - "firebase_*"
      widgetbook:
        patterns:
          - "widgetbook"
          - "widgetbook_annotation"
          - "widgetbook_generator"
    ignore:
      - dependency-name: "collection"
      - dependency-name: "intl"
      - dependency-name: "flutter"
      - dependency-name: "flutter_localizations"
      - dependency-name: "flutter_test"
      - dependency-name: "flutter_web_plugins"
      - dependency-name: "sdk"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  # Gradle の依存関係を管理
  - package-ecosystem: "gradle"
    directory: "/app/mobile/android"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      gradle-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      gradle-wrapper:
        patterns:
          - "gradle"
          - "gradle-wrapper"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  # CocoaPods の依存関係を管理
  - package-ecosystem: "bundler"
    directory: "/app/mobile/ios"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      cocoapods-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  # Docker の依存関係を管理
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      docker-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
