# Default labels
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "dependencies"
  color: "1d76db"
  description: "Pull requests that update a dependency file"

- name: "DO NOT MERGE"
  color: "b60205"

- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "good first issue"
  color: "fe9b9c"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "ignore for release"
  color: "bfd4f2"
  description: "Exclude from Release Notes"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "work in progress"
  color: "e5d19e"

# Type labels
- name: "type/feature"
  color: "ededed"
  description: "A new feature"
  from_name: "@type/feature"

- name: "type/fix"
  color: "ededed"
  description: "A bug fix"
  from_name: "@type/fix"

- name: "type/docs"
  color: "ededed"
  description: "Documentation only changes"
  from_name: "@type/docs"

- name: "type/style"
  color: "ededed"
  description: "Changes that do not affect the meaning of the code"
  from_name: "@type/style"

- name: "type/refactor"
  color: "ededed"
  description: "A code change that neither fixes a bug nor adds a feature"
  from_name: "@type/refactor"

- name: "type/perf"
  color: "ededed"
  description: "A code change that improves performance"
  from_name: "@type/perf"

- name: "type/test"
  color: "ededed"
  description: "Adding missing tests or correcting existing tests"
  from_name: "@type/test"

- name: "type/build"
  color: "ededed"
  description: "Changes that affect the build system or external dependencies"
  from_name: "@type/build"

- name: "type/ci"
  color: "ededed"
  description: "Changes to our CI configuration files and scripts"
  from_name: "@type/ci"

- name: "type/chore"
  color: "ededed"
  description: "Other changes that don't modify src or test files"
  from_name: "@type/chore"

- name: "type/revert"
  color: "ededed"
  description: "Reverts a previous commit"
  from_name: "@type/revert"

# <!-- This is an auto-generated label -->
# App Package labels
- name: "@application"
  color: "e261d6"
  description: "Application development"

- name: "@backend"
  color: "4372d0"
  description: "Backend development"

- name: "@catalog"
  color: "d4f227"
  description: "Catalog development"

# Core Package labels
- name: "@core/analytics"
  color: "0b2ebd"

- name: "@core/common"
  color: "e99695"

- name: "@core/data"
  color: "50D413"

- name: "@core/database"
  color: "90bf94"

- name: "@core/datastore"
  color: "1997D2"

- name: "@core/designsystem"
  color: "936116"

- name: "@core/domain"
  color: "DC79FD"

- name: "@core/model"
  color: "D1A70E"

- name: "@core/network"
  color: "630D81"

- name: "@core/testing"
  color: "667168"

- name: "@core/ui"
  color: "b1ade8"

# Feature Package labels
- name: "@feature/auth"
  color: "48360E"

- name: "@feature/home"
  color: "3bc0ec"

- name: "@feature/quest"
  color: "6fe0ba"

- name: "@feature/settings"
  color: "1e266d"
