version: 1

labels:
  # Type labels
  - label: "@type/fix"
    title: '^:bug:.*'

  - label: "@type/feature"
    title: '^(:sparkles:|:tada:|:art:).*'

  - label: "@type/improve"
    title: '^(:\+1:|:recycle:|:rocket:).*'

  - label: "@type/docs"
    title: '^:books:.*'
    files:
      - "docs/.+"
      - "**/README\.md"

  - label: "@type/build"
    title: '^:up:.*'
    files:
      - "**/pubspec\.yaml"
      - "**/melos\.yaml"

  - label: "@type/ci"
    title: '^:wrench:.*'
    files:
      - '\.github/.+'
      - 'tools/.+'

  # Core Package labels
  - label: "@core/network"
    files:
      - "core/network/.+"

  - label: "@core/database"
    files:
      - "core/database/.+"

  - label: "@core/datastore"
    files:
      - "core/datastore/.+"

  - label: "@core/data"
    files:
      - "core/data/.+"

  - label: "@core/model"
    files:
      - "core/model/.+"

  - label: "@core/domain"
    files:
      - "core/domain/.+"

  - label: "@core/testing"
    files:
      - "core/testing/.+"

  - label: "@core/ui"
    files:
      - "core/ui/.+"

  - label: "@core/design"
    files:
      - "core/design/.+"

  - label: "@core/common"
    files:
      - "core/common/.+"

  # Feature Package labels
  # TBD

  # App labels
  - label: "@application"
    files:
      - "app/.+"
