# noinspection YAMLSchemaValidation
version: 1

labels:
  # Type labels
  - label: "type/feature"
    title: '^\[.*?\]\s*feat(?:\(.+?\))?\!?:'

  - label: "type/fix"
    title: '^\[.*?\]\s*fix(?:\(.+?\))?\!?:'

  - label: "type/docs"
    title: '^\[.*?\]\s*docs(?:\(.+?\))?\!?:'
    files:
      - "docs/.+"
      - "**/README.md$"

  - label: "type/style"
    title: '^\[.*?\]\s*style(?:\(.+?\))?\!?:'

  - label: "type/refactor"
    title: '^\[.*?\]\s*refactor(?:\(.+?\))?\!?:'

  - label: "type/perf"
    title: '^\[.*?\]\s*perf(?:\(.+?\))?\!?:'

  - label: "type/test"
    title: '^\[.*?\]\s*test(?:\(.+?\))?\!?:'

  - label: "type/build"
    title: '^\[.*?\]\s*build(?:\(.+?\))?\!?:'
    files:
      - "**/pubspec.yaml$"
      - "**/melos.yaml$"

  - label: "type/ci"
    title: '^\[.*?\]\s*ci(?:\(.+?\))?\!?:'
    files:
      - '\.github/.+'
      - "tool/.+"

  - label: "type/chore"
    title: '^\[.*?\]\s*chore(?:\(.+?\))?\!?:'

  - label: "type/revert"
    title: '^\[.*?\]\s*revert(?:\(.+?\))?\!?:'

  # <!-- This is an auto-generated label -->
  - label: "@app/mobile"
    files:
      - app/mobile/.+

  - label: "@backend"
    files:
      - backend/.+

  - label: "@catalog"
    files:
      - catalog/.+

  - label: "@core/analytics"
    files:
      - core/analytics/.+

  - label: "@core/analytics_firebase"
    files:
      - core/analytics_firebase/.+

  - label: "@core/authenticator"
    files:
      - core/authenticator/.+

  - label: "@core/common"
    files:
      - core/common/.+

  - label: "@core/data"
    files:
      - core/data/.+

  - label: "@core/database"
    files:
      - core/database/.+

  - label: "@core/database_isar"
    files:
      - core/database_isar/.+

  - label: "@core/datastore"
    files:
      - core/datastore/.+

  - label: "@core/designsystem"
    files:
      - core/designsystem/.+

  - label: "@core/domain"
    files:
      - core/domain/.+

  - label: "@core/model"
    files:
      - core/model/.+

  - label: "@core/network"
    files:
      - core/network/.+

  - label: "@core/network_ferry"
    files:
      - core/network_ferry/.+

  - label: "@core/testing"
    files:
      - core/testing/.+

  - label: "@core/ui"
    files:
      - core/ui/.+

  - label: "@feature/auth"
    files:
      - feature/auth/.+

  - label: "@feature/feed"
    files:
      - feature/feed/.+

  - label: "@feature/home"
    files:
      - feature/home/.+

  - label: "@feature/quest"
    files:
      - feature/quest/.+

  - label: "@feature/settings"
    files:
      - feature/settings/.+
