name: core_analytics
description: This package provides functions for analysis.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.4.3

dependencies:
  core_common:
    path: ../common

dev_dependencies:
  test: 1.25.7
  yumemi_lints: 2.1.0
