name: core_analytics
description: This package provides functions for analysis.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.3.3

dependencies:
  core_common:
    path: ../common

dev_dependencies:
  test: 1.25.4
  yumemi_lints: 1.7.0
