name: core_analytics
description: This package provides functions for analysis.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.0

dependencies:
  core_common:
    path: ../common
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.11
  riverpod_generator: 2.4.2
  yumemi_lints: 2.1.0
