name: core_analytics
description: This package provides functions for analysis.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.4

dependencies:
  core_common:
    path: ../common
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.13
  riverpod_generator: 2.6.3
  yumemi_lints: 2.2.0
