# When flutter version is updated, you should update this version.
include: package:yumemi_lints/dart/3.4/recommended.yaml

analyzer:
  exclude:
    - "**/build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/firebase_options.dart"
    - "bricks/**"
