name: "tobe-app"

services:
  backend:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    ports:
      - "12129:8080"
    networks:
      - default
      - tobe-network

networks:
  tobe-network:
    external: true
