name: "asis-app"

services:
  backend:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    ports:
      - "12129:8080"
    networks:
      - default
      - asis-network

networks:
  asis-network:
    external: true
