name: "asis-app"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "2110:8080"
    networks:
      - default
      - asis-network

networks:
  asis-network:
    external: true
