# When you use this template, you must change this name field.
name: asis

sdkPath: .fvm/flutter_sdk

packages:
  - app
  - core/*
  - feature/*

command:
  bootstrap:
    environment:
      sdk: 3.2.4
      flutter: 3.16.7
    dev_dependencies:
      test: 1.24.0
      yumemi_lints: 1.3.0

scripts:
  analyze:
    run: |
      melos exec -- "flutter analyze"
    description: Run analyze.
    packageFilters:
      flutter: true
      dirExists: lib
  gen:code:
    run: |
      melos exec -c 1 -- "flutter gen-l10n"
    description: Run build_runner.
    packageFilters:
      flutter: true
      fileExists: "l10n.yaml"
  gen:l10n:
    run: |
      melos exec -c 1 -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run build_runner.
    packageFilters:
      flutter: true
      dependsOn: "build_runner"
  fix:
    run: |
      melos exec -- "dart fix --apply lib"
    description: Run dart fix.
    packageFilters:
      flutter: true
      dirExists: lib
  fix:check:
    run: |
      melos exec -- "dart fix --dry-run lib"
    description: Check dart fix.
    packageFilters:
      flutter: true
      dirExists: lib
  format:
    run: |
      melos exec -- "dart format lib"
    description: Run format.
    packageFilters:
      flutter: true
      dirExists: lib
  format:check:
    run: |
      melos exec -- "dart format lib --dry-run --set-exit-if-changed"
    description: Check format.
    packageFilters:
      flutter: true
      dirExists: lib

  test:
    run: |
      melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run flutter test.
  test:dart:
    run: |
      melos exec -c 10 --fail-fast -- "dart test"
    description: Run Dart test.
    packageFilters:
      flutter: false
      dirExists: test
  test:flutter:
    run: |
      melos exec -c 10 --fail-fast -- "flutter test --coverage"
    description: Run flutter test.
    packageFilters:
      flutter: true
      dirExists: test
