# When you use this template, you must change this name field.
name: asis

packages:
  - app
  - backend
  - catalog
  - core/*
  - feature/*

ide:
  intellij:
    enabled: true

versions:
  - &isar 4.0.3

command:
  bootstrap:
    environment:
      sdk: 3.4.0
      flutter: 3.22.0
    dependencies:
      flutter_riverpod: 2.5.1
      freezed_annotation: 2.4.1
      go_router: 14.1.2
      hooks_riverpod: 2.5.1
      isar:
        hosted: https://pub.isar-community.dev/
        version: *isar
      isar_flutter_libs:
        hosted: https://pub.isar-community.dev/
        version: *isar
      riverpod: 2.5.1
      riverpod_annotation: 2.3.5
    dev_dependencies:
      build_runner: 2.4.10
      freezed: 2.5.2
      test: 1.25.5
      riverpod_generator: 2.4.2
      riverpod_lint: 2.3.8
      yumemi_lints: 1.7.0

scripts:
  # analyze
  analyze:
    run: melos run analyze:dart --no-select && melos run analyze:flutter --no-select
    description: Run analyze.
  analyze:dart:
    exec: dart analyze
    description: Run analyze.
    packageFilters:
      flutter: false
      dirExists: lib
  analyze:flutter:
    exec: flutter analyze
    description: Run analyze.
    packageFilters:
      flutter: true
      dirExists: lib

  # gen
  gen:
    run: melos run gen:dart --no-select && melos run gen:flutter --no-select
    description: Run analyze.
  gen:dart:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    description: Run build_runner.
    packageFilters:
      flutter: false
      dependsOn: "build_runner"
  gen:flutter:
    run: flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    description: Run build_runner.
    packageFilters:
      flutter: true
      dependsOn: "build_runner"
  gen:l10n:
    run: flutter gen-l10n
    exec:
      concurrency: 1
    description: Generate l10n.
    packageFilters:
      flutter: true
      fileExists: "l10n.yaml"
  fix:
    exec: dart fix --apply lib
    description: Run dart fix.
    packageFilters:
      flutter: true
      dirExists: lib
  fix:check:
    exec: dart fix --dry-run lib
    description: Check dart fix.
    packageFilters:
      flutter: true
      dirExists: lib
  format:
    exec: dart format lib
    description: Run format.
    packageFilters:
      flutter: true
      dirExists: lib
  format:check:
    exec: dart format lib --output=none --set-exit-if-changed
    description: Check format.
    packageFilters:
      flutter: true
      dirExists: lib

  test:
    run: very_good test --recursive --coverage
    exec:
      concurrency: 10
      failFast: true
    description: Run test.
    packageFilters:
      dirExists: test

  # ci
  ci:analyze:
    run: melos run ci:analyze:dart --no-select && melos run ci:analyze:flutter --no-select
    description: Run analyze.
  ci:analyze:dart:
    run: dart analyze
    exec:
      concurrency: 10
      failFast: true
    description: Run analyze.
    packageFilters:
      flutter: false
      dirExists: lib
  ci:analyze:flutter:
    run: flutter analyze
    exec:
      concurrency: 10
      failFast: true
    description: Run analyze.
    packageFilters:
      flutter: true
      dirExists: lib
  ci:test:
    run: very_good test --recursive --coverage
    exec:
      concurrency: 2
      failFast: true
    description: Run test.
    packageFilters:
      dirExists: test