# When you use this template, you must change this name field.
name: tobe

environment:
  sdk: 3.6.0

workspace:
  - app/backend
  - app/catalog
  - app/mobile
  - core/analytics
  - core/analytics_firebase
  - core/authenticator
  - core/common
  - core/data
  - core/database
  - core/database_isar
  - core/datastore
  - core/designsystem
  - core/domain
  - core/model
  - core/network
  - core/network_model
  - core/testing
  - core/ui
  - feature/auth
  - feature/debug
  - feature/feed
  - feature/home
  - feature/onboarding
  - feature/quest
  - feature/settings

dev_dependencies:
  grinder: 0.9.5
  melos: 6.2.0
  path: 1.9.1
  yaml: 3.1.2
  yaml_edit: 2.2.1
  yumemi_lints: 2.2.0

dependency_overrides:
  file: 7.0.0
  meta: 1.15.0
  path: 1.9.1
  test_api: 0.7.2
  web: 0.4.2
