# When you use this template, you must change this name field.
name: asis

environment:
  sdk: 3.5.3

dependency_overrides:
  # workaround
  # yumemi_lints >=2.0.0 depends on file ^6.1.4 and melos 6.0.0 depends on file ^7.0.0
  file: 7.0.0

dev_dependencies:
  grinder: 0.9.5
  melos: 6.2.0
  path: 1.9.1
  yaml: 3.1.2
  yaml_edit: 2.2.1
  yumemi_lints: 2.2.0
