# When you use this template, you must change this name field.
name: asis

environment:
  sdk: 3.4.1

dependency_overrides:
  # workaround
  # yumemi_lints >=2.0.0 depends on file ^6.1.4 and melos 6.0.0 depends on file ^7.0.0
  file: 7.0.0

dev_dependencies:
  melos: 6.0.0
  yumemi_lints: 2.1.0
