# When you use this template, you must change this name field.
name: tobe

environment:
  sdk: ^3.8.0

workspace:
  - app/backend
  - app/catalog
  - app/mobile
  - core/analytics
  - core/analytics_firebase
  - core/authenticator
  - core/common
  - core/data
  - core/database
  - core/database_drift
  - core/datastore
  - core/designsystem
  - core/domain
  - core/model
  - core/network
  - core/network_model
  - core/testing
  - core/ui
  - feature/auth
  - feature/debug
  - feature/feed
  - feature/home
  - feature/onboarding
  - feature/quest
  - feature/settings

dev_dependencies:
  melos: 7.0.0-dev.9
  yumemi_lints: 4.0.0

dependency_overrides:
  analyzer: 6.10.0
  collection: 1.19.1
  file: 7.0.0
  intl: 0.20.2
  meta: 1.15.0
  test_api: 0.7.4
  web: 0.4.2

melos:
  ide:
    intellij:
      enabled: false
  
  command:
    bootstrap:
      hooks:
        post: melos bootstrap:post_hooks
  
  scripts:
    # hooks
    bootstrap:post_hooks:
      steps:
        - gen:app_mobile
    
    # analyze
    analyze:
      run: melos run analyze:dart --no-select && melos run analyze:flutter --no-select
      description: Run analyze.
    analyze:dart:
      exec: dart analyze
      description: Run analyze.
      packageFilters:
        flutter: false
        dirExists: lib
    analyze:flutter:
      exec: flutter analyze
      description: Run analyze.
      packageFilters:
        flutter: true
        dirExists: lib
    
    # gen
    gen:
      exec: dart run build_runner build --delete-conflicting-outputs
      description: Run build_runner.
      packageFilters:
        dependsOn: "build_runner"
    gen:watch:
      exec: dart run build_runner watch --delete-conflicting-outputs
      description: Run build_runner.
      packageFilters:
        dependsOn: "build_runner"
    gen:app_mobile:
      run: |
        melos exec --scope="app_mobile" \
          dart run build_runner build --delete-conflicting-outputs
      description: Run build_runner.
    gen:l10n:
      run: flutter gen-l10n
      exec:
        concurrency: 1
      description: Generate l10n.
      packageFilters:
        flutter: true
        fileExists: "l10n.yaml"
    gen:clean:
      exec: dart pub run build_runner clean
      description: Run build_runner.
      packageFilters:
        dependsOn: "build_runner"
    
    fix:
      exec: dart fix --apply lib
      description: Run dart fix.
      packageFilters:
        flutter: true
        dirExists: lib
    fix:check:
      exec: dart fix --dry-run lib
      description: Check dart fix.
      packageFilters:
        flutter: true
        dirExists: lib
    format:
      exec: dart format lib
      description: Run format.
      packageFilters:
        flutter: true
        dirExists: lib
    format:check:
      exec: dart format lib --output=none --set-exit-if-changed
      description: Check format.
      packageFilters:
        flutter: true
        dirExists: lib
    
    test:
      run: very_good test --recursive --coverage
      exec:
        concurrency: 10
        failFast: true
      description: Run test.
      packageFilters:
        dirExists: test
    
    # upgrade
    upgrade:
      description: dart pub upgrade & flutter pub upgrade.
      concurrency: 1
      steps:
        - upgrade:dart
        - upgrade:flutter
    upgrade:dart:
      exec: dart pub upgrade
      concurrency: 1
      description: dart pub upgrade.
      packageFilters:
        flutter: false
    upgrade:flutter:
      exec: flutter pub upgrade
      concurrency: 1
      description: flutter pub upgrade.
      packageFilters:
        flutter: true
    
    # ci
    ci:gen:
      description: generate codes.
      concurrency: 1
      steps:
        - melos gen
        - melos gen:l10n
    ci:test:
      run: very_good test --recursive --coverage
      exec:
        concurrency: 1
        failFast: true
      description: Run test.
      packageFilters:
        dirExists: test
