name: core_network_model
description: This package provides network operations.
publish_to: "none"

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: 2.4.14
  freezed: 3.0.6
  json_serializable: 6.8.0
  yumemi_lints: 4.0.0
