name: core_network_model
description: This package provides network operations.
publish_to: "none"

environment:
  sdk: 3.8.0

resolution: workspace

dependencies:
  freezed_annotation: 3.0.0
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: 2.4.15
  freezed: 3.0.6
  json_serializable: 6.9.5
  yumemi_lints: 4.1.1
