name: core_common
description: This package provides convenience functions and other functions commonly used in packages.
publish_to: "none"

environment:
  sdk: 3.8.0

resolution: workspace

dependencies:
  anyhow: 1.3.2
  collection: 1.19.1
  rust_core: 1.3.7
  simple_logger: 1.10.0

dev_dependencies:
  test: 1.26.2
  yumemi_lints: 4.1.1
