name: backend
description: An new Dart Frog application
version: 0.1.0
publish_to: none

environment:
  sdk: 3.5.0-219.0.dev

dependencies:
  dart_frog: 1.1.0

dev_dependencies:
  mocktail: 1.0.3
  test: 1.25.7
  yumemi_lints: 2.1.0
