name: feature_settings
description: "This package provides settings features."
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.4.1
  flutter: 3.22.1

dependencies:
  core_common:
    path: ../../core/common
  core_designsystem:
    path: ../../core/designsystem
  core_domain:
    path: ../../core/domain
  core_model:
    path: ../../core/model
  core_ui:
    path: ../../core/ui
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  go_router: 14.1.3
  hooks_riverpod: 2.5.1

dev_dependencies:
  core_testing:
    path: ../../core/testing
  flutter_test:
    sdk: flutter
  yumemi_lints: 1.7.0

flutter:
