name: feature_home
description: "This package provides home features."
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.0-219.0.dev
  flutter: 3.23.0-0.1.pre

dependencies:
  core_common:
    path: ../../core/common
  core_designsystem:
    path: ../../core/designsystem
  core_domain:
    path: ../../core/domain
  core_model:
    path: ../../core/model
  core_ui:
    path: ../../core/ui
  flutter:
    sdk: flutter
  go_router: 14.1.4
  hooks_riverpod: 2.5.1

dev_dependencies:
  core_testing:
    path: ../../core/testing
  flutter_test:
    sdk: flutter
  yumemi_lints: 2.1.0

flutter:
