name: feature_home
description: "This package provides home features."
publish_to: "none"

environment:
  sdk: 3.6.0
  flutter: 3.27.1

resolution: workspace

dependencies:
  core_common: any
  core_designsystem: any
  core_domain: any
  core_model: any
  core_ui: any
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: 2.6.1
  intl: 0.19.0

dev_dependencies:
  core_testing: any
  flutter_test:
    sdk: flutter
  yumemi_lints: 2.2.0

flutter:
