name: core_analytics_firebase
description: This package provides functions for analysis.
publish_to: "none"

environment:
  sdk: 3.8.0
  flutter: 3.32.0

resolution: workspace

dependencies:
  core_analytics: any
  core_common: any
  firebase_analytics: 11.5.0
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.15
  riverpod_generator: 2.6.5
  test: 1.26.2
  yumemi_lints: 4.0.0
