name: core_analytics_firebase
description: This package provides functions for analysis.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.4.3
  flutter: 3.22.2

dependencies:
  core_analytics:
    path: ../analytics
  core_common:
    path: ../common
  firebase_analytics: 11.0.0
  riverpod_annotation: 2.3.5

dependency_overrides:
  # workaround
  meta: 1.15.0
  # workaround
  test_api: 0.7.2

dev_dependencies:
  build_runner: 2.4.11
  core_testing:
    path: ../testing
  riverpod_generator: 2.4.2
  test: 1.25.7
  yumemi_lints: 2.1.0
