name: core_model
description: This package provides model classes.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.2.4

dependencies:
  core_common:
    path: ../common
  riverpod: 2.4.9
  riverpod_annotation: 2.3.3

dev_dependencies:
  build_runner: 2.4.8
  riverpod_generator: 2.3.9
  test: 1.24.0
  yumemi_lints: 1.4.0
