name: core_model
description: This package provides model classes.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.2.4

dependencies:
  core_common:
    path: ../common

dev_dependencies:
  test: 1.24.0
  yumemi_lints: 1.4.0
