name: core_model
description: This package provides model classes.
publish_to: "none"

environment:
  sdk: 3.8.0

resolution: workspace

dependencies:
  core_common: any
  freezed_annotation: 3.0.0
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.14
  freezed: 3.0.6
  riverpod_generator: 2.6.5
  test: 1.25.14
  yumemi_lints: 4.0.0
