name: app_mobile
description: "TOBE Mobile App"
publish_to: "none"
version: 0.0.1+2

environment:
  sdk: 3.8.0
  flutter: 3.32.0

resolution: workspace

dependencies:
  core_analytics_firebase: any
  core_authenticator: any
  core_common: any
  core_database_drift: any
  core_datastore: any
  core_designsystem: any
  core_domain: any
  core_model: any
  core_network: any
  core_ui: any
  cupertino_icons: 1.0.8
  dynamic_color: 1.7.0
  envied: 1.1.1
  feature_announcement: any
  feature_auth: any
  feature_debug: any
  feature_feed: any
  feature_home: any
  feature_my: any
  feature_onboarding: any
  feature_quest: any
  feature_settings: any
  firebase_analytics: 11.4.6
  firebase_auth: 5.5.4
  firebase_core: 3.13.1
  firebase_remote_config: 5.4.4
  flutter:
    sdk: flutter
  flutter_hooks: 0.21.2
  flutter_localizations:
    sdk: flutter
  go_router: 15.1.0
  hooks_riverpod: 2.6.1
  intl: 0.20.2
  package_info_plus: 8.3.0
  path_provider: 2.1.5
  riverpod_annotation: 2.6.1
  shared_preferences: 2.5.3
  url_launcher: 6.3.1

dev_dependencies:
  build_runner: 2.4.15
  envied_generator: 1.1.1
  riverpod_generator: 2.6.5
  yumemi_lints: 4.0.0

flutter:
  generate: true
  uses-material-design: true
