name: catalog
description: "ASIS Catalog"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: 3.3.2

dependencies:
  core_designsystem:
    # noinspection DartPathPackageReference
    path: ../core/designsystem
  core_model:
    # noinspection DartPathPackageReference
    path: ../core/model
  cupertino_icons: 1.0.6
  dynamic_color: 1.7.0
  feature_auth:
    # noinspection DartPathPackageReference
    path: ../feature/auth
  feature_home:
    # noinspection DartPathPackageReference
    path: ../feature/home
  feature_quest:
    # noinspection DartPathPackageReference
    path: ../feature/quest
  feature_settings:
    # noinspection DartPathPackageReference
    path: ../feature/settings
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  widgetbook: 3.7.1
  widgetbook_annotation: 3.1.0

dev_dependencies:
  build_runner: 2.4.8
  widgetbook_generator: 3.7.0
  yumemi_lints: 1.7.0

flutter:
  uses-material-design: true
