name: cli
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: 3.5.0-180.3.beta

dependencies:
  args: 2.4.2
  cli_completion: 0.5.0
  mason_logger: 0.2.12
  path: 1.9.0
  pub_updater: 0.4.0
  yaml: 3.1.2
  yaml_edit: 2.2.1

dev_dependencies:
  build_runner: 2.4.8
  build_verify: 3.1.0
  build_version: 2.1.1
  mocktail: 1.0.3
  test: 1.25.7
  yumemi_lints: 2.1.0

executables:
  cli:
