name: asis_app
description: "ASIS App"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: 3.3.4

dependencies:
  core_common:
    # noinspection DartPathPackageReference
    path: ../core/common
  core_database:
    # noinspection DartPathPackageReference
    path: ../core/database
  core_designsystem:
    # noinspection DartPathPackageReference
    path: ../core/designsystem
  core_model:
    # noinspection DartPathPackageReference
    path: ../core/model
  cupertino_icons: 1.0.8
  device_preview: 1.1.0
  dynamic_color: 1.7.0
  feature_auth:
    # noinspection DartPathPackageReference
    path: ../feature/auth
  feature_home:
    # noinspection DartPathPackageReference
    path: ../feature/home
  feature_quest:
    # noinspection DartPathPackageReference
    path: ../feature/quest
  feature_settings:
    # noinspection DartPathPackageReference
    path: ../feature/settings
  firebase_core: 2.30.1
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  go_router: 14.0.1
  isar_flutter_libs: 4.0.0-dev.14
  package_info_plus: 8.0.0
  riverpod_annotation: 2.3.5

dependency_overrides:
  # workaround
  # https://stackoverflow.com/questions/77947590/error-the-type-jsobject-cant-be-used-as-supertype-while-deploying-flutter
  web: 0.4.2

dev_dependencies:
  build_runner: 2.4.9
  flutter_test:
    sdk: flutter
  go_router_builder: 2.6.1
  riverpod_generator: 2.4.0
  yumemi_lints: 1.7.0

flutter:
  uses-material-design: true
