name: asis_app
description: "ASIS App"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: 3.2.4

dependencies:
  core_designsystem:
    path: ../core/designsystem
  cupertino_icons: 1.0.6
  dynamic_color: 1.6.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: 1.4.0

flutter:
  uses-material-design: true
