name: app
description: "ASIS App"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: 3.5.0-180.3.beta
  flutter: 3.23.0-0.1.pre

dependencies:
  core_analytics_firebase:
    # noinspection DartPathPackageReference
    path: ../core/analytics_firebase
  core_authenticator:
    # noinspection DartPathPackageReference
    path: ../core/authenticator
  core_common:
    # noinspection DartPathPackageReference
    path: ../core/common
  core_database_isar:
    # noinspection DartPathPackageReference
    path: ../core/database_isar
  core_datastore:
    # noinspection DartPathPackageReference
    path: ../core/datastore
  core_designsystem:
    # noinspection DartPathPackageReference
    path: ../core/designsystem
  core_domain:
    # noinspection DartPathPackageReference
    path: ../core/domain
  core_model:
    # noinspection DartPathPackageReference
    path: ../core/model
  core_network_ferry:
    # noinspection DartPathPackageReference
    path: ../core/network_ferry
  core_ui:
    # noinspection DartPathPackageReference
    path: ../core/ui
  cupertino_icons: 1.0.8
  dynamic_color: 1.7.0
  envied: 0.5.4+1
  feature_auth:
    # noinspection DartPathPackageReference
    path: ../feature/auth
  feature_feed:
    # noinspection DartPathPackageReference
    path: ../feature/feed
  feature_home:
    # noinspection DartPathPackageReference
    path: ../feature/home
  feature_quest:
    # noinspection DartPathPackageReference
    path: ../feature/quest
  feature_settings:
    # noinspection DartPathPackageReference
    path: ../feature/settings
  firebase_analytics: 11.0.1
  firebase_auth: 5.1.0
  firebase_core: 3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.5.1
  go_router: 14.2.0
  intl: 0.19.0
  isar:
    hosted: https://pub.isar-community.dev/
    version: 4.0.3
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev/
    version: 4.0.3
  package_info_plus: 8.0.0
  path_provider: 2.1.3
  riverpod_annotation: 2.3.5
  shared_preferences: 2.2.3

dependency_overrides:
  # workaround
  # So, because feature_quest depends on both flutter_test from sdk and riverpod_generator 2.4.2, version solving failed.
  meta: 1.15.0
  # workaround
  # https://stackoverflow.com/questions/77947590/error-the-type-jsobject-cant-be-used-as-supertype-while-deploying-flutter
  web: 0.4.2

dev_dependencies:
  build_runner: 2.4.11
  envied_generator: 0.5.4+1
  flutter_test:
    sdk: flutter
  go_router_builder: 2.7.0
  riverpod_generator: 2.4.2
  yumemi_lints: 2.1.0

flutter:
  uses-material-design: true
