name: core_network
description: This package provides network operations.
publish_to: "none"

environment:
  sdk: 3.8.0

resolution: workspace

dependencies:
  core_authenticator: any
  core_common: any
  core_model: any
  core_network_model: any
  dio: 5.8.0+1
  freezed_annotation: 3.0.0
  retrofit: 4.4.2
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.15
  freezed: 3.0.6
  retrofit_generator: 9.2.0
  riverpod_generator: 2.6.5
  yumemi_lints: 4.0.0
