name: core_network
description: This package provides network operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.4.4

dependencies:
  core_authenticator:
    path: ../authenticator
  core_common:
    path: ../common
  core_model:
    path: ../model
  core_network_model:
    path: ../network_model
  dio: 5.5.0+1
  freezed_annotation: 2.4.4
  retrofit: 4.1.0
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.12
  freezed: 2.5.7
  retrofit_generator: 8.1.2
  riverpod_generator: 2.4.2
  yumemi_lints: 2.1.0
