name: core_network
description: This package provides network operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.4.1

dependencies:
  core_authenticator:
    path: ../authenticator
  core_common:
    path: ../common
  core_model:
    path: ../model
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.10
  core_testing:
    path: ../testing
  riverpod_generator: 2.4.2
  test: 1.25.5
  yumemi_lints: 1.7.0
