name: core_network
description: This package provides network operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.0-180.3.beta

dependencies:
  core_authenticator:
    path: ../authenticator
  core_common:
    path: ../common
  core_model:
    path: ../model
  freezed_annotation: 2.4.1
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.11
  freezed: 2.5.3
  riverpod_generator: 2.4.2
  yumemi_lints: 2.1.0
