name: core_database_isar
description: This package provides local database operations using Isar.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.0-219.0.dev

dependencies:
  core_common:
    path: ../common
  core_database:
    path: ../database
  core_model:
    path: ../model
  isar:
    hosted: https://pub.isar-community.dev/
    version: 4.0.3
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.11
  core_testing:
    path: ../testing
  riverpod_generator: 2.4.2
  test: 1.25.7
  yumemi_lints: 2.1.0
