targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: app_backend|lib/graphql/schema.graphql
          type_overrides:
            uuid:
              name: String
            timestamptz:
              name: DateTime
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: app_backend|lib/graphql/schema.graphql
          type_overrides:
            uuid:
              name: String
            timestamptz:
              name: DateTime
          custom_serializers:
            - import: 'package:app_backend/graphql/serializer/timestamptz_serializer.dart'
              name: TimestamptzSerializer
