name: core_designsystem
description: This package provides style definitions, themes, etc.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.0-180.3.beta
  flutter: 3.23.0-0.1.pre

dependencies:
  core_common:
    path: ../common
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: 0.1.11
  gap: 3.0.1

dev_dependencies:
  core_testing:
    path: ../testing
  flutter_test:
    sdk: flutter
  yumemi_lints: 2.1.0

flutter:
