name: core_designsystem
description: This package provides style definitions, themes, etc.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.2.4
  flutter: 3.16.7

dependencies:
  core_common:
    path: ../common
  flutter:
    sdk: flutter

dev_dependencies:
  core_testing:
    path: ../testing
  flutter_test:
    sdk: flutter
  yumemi_lints: 1.3.0

flutter:
