name: core_designsystem
description: This package provides style definitions, themes, etc.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.3.3
  flutter: 3.19.5

dependencies:
  core_common:
    path: ../common
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: 0.1.10+1

dev_dependencies:
  core_testing:
    path: ../testing
  flutter_test:
    sdk: flutter
  yumemi_lints: 1.7.0

flutter:
