name: core_designsystem
description: This package provides style definitions, themes, etc.
publish_to: "none"

environment:
  sdk: 3.8.0
  flutter: 3.32.0

resolution: workspace

dependencies:
  core_common: any
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: 0.3.3+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.1.0
  gap: 3.0.1
  intl: 0.20.2

dev_dependencies:
  build_runner: 2.4.15
  core_testing: any
  flutter_gen_runner: 5.10.0
  flutter_test:
    sdk: flutter
  yumemi_lints: 4.1.1

flutter:
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
