name: catalog
description: "ASIS Catalog"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: 3.4.4
  flutter: 3.22.3

dependencies:
  core_designsystem:
    path: ../../core/designsystem
  core_model:
    path: ../../core/model
  core_ui:
    path: ../../core/ui
  cupertino_icons: 1.0.8
  dynamic_color: 1.7.0
  feature_auth:
    path: ../../feature/auth
  feature_feed:
    path: ../../feature/feed
  feature_home:
    path: ../../feature/home
  feature_quest:
    path: ../../feature/quest
  feature_settings:
    path: ../../feature/settings
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  widgetbook: 3.8.1
  widgetbook_annotation: 3.1.0

dev_dependencies:
  build_runner: 2.4.12
  widgetbook_generator: 3.8.0
  yumemi_lints: 2.1.0

flutter:
  uses-material-design: true
