name: app_catalog
description: "TOBE Catalog"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: 3.5.4
  flutter: 3.24.4

dependencies:
  core_designsystem:
    path: ../../core/designsystem
  core_model:
    path: ../../core/model
  core_ui:
    path: ../../core/ui
  cupertino_icons: 1.0.8
  dynamic_color: 1.7.0
  feature_auth:
    path: ../../feature/auth
  feature_feed:
    path: ../../feature/feed
  feature_home:
    path: ../../feature/home
  feature_quest:
    path: ../../feature/quest
  feature_settings:
    path: ../../feature/settings
  flutter:
    sdk: flutter
  flutter_riverpod: 2.6.1
  widgetbook: 3.10.0
  widgetbook_annotation: 3.2.0

dev_dependencies:
  build_runner: 2.4.13
  widgetbook_generator: 3.9.0
  yumemi_lints: 2.2.0

flutter:
  uses-material-design: true
