name: core_network_ferry
description: This package provides network operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.0-180.3.beta

dependencies:
  core_authenticator:
    path: ../authenticator
  core_common:
    path: ../common
  core_model:
    path: ../model
  core_network:
    path: ../network
  ferry: 0.16.0+1
  gql_code_builder: 0.12.0
  gql_http_link: 1.1.0
  riverpod_annotation: 2.3.5

dependency_overrides:
  # workaround
  gql_code_builder: 0.12.0

dev_dependencies:
  build_runner: 2.4.11
  ferry_generator: 0.10.0
  riverpod_generator: 2.4.2
  test: 1.25.7
  yumemi_lints: 2.1.0
