name: feature_my
description: My page feature module for TOBE app.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: 3.8.0
  flutter: 3.32.0

resolution: workspace

dependencies:
  core_authenticator: any
  core_common: any
  core_designsystem: any
  core_domain: any
  core_model: any
  core_ui: any
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: 0.3.3+1
  flutter_hooks: 0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.6.1
  freezed_annotation: 3.0.0
  gap: 3.0.1
  go_router: 15.1.0
  hooks_riverpod: 2.6.1
  intl: 0.20.2
  json_annotation: 4.9.0
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.15
  flutter_test:
    sdk: flutter
  freezed: 3.0.6
  json_serializable: 6.9.5
  mocktail: 1.0.4
  riverpod_generator: 2.6.5

flutter:
  generate: true