name: core_database_drift
description: This package provides local database operations using Drift.
publish_to: "none"

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  core_common: any
  core_database: any
  core_model: any
  drift: 2.22.1
  flutter:
    sdk: flutter
  path: 1.9.1
  path_provider: 2.1.5
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  sqlite3_flutter_libs: 0.5.27

dev_dependencies:
  build_runner: 2.4.14
  core_testing: any
  drift_dev: 2.22.1
  riverpod_generator: 2.6.5
  test: 1.25.14
  yumemi_lints: 4.0.0