name: core_ui
description: This package provides a UI that depends on the model class and is used by all packages.
publish_to: "none"

environment:
  sdk: 3.8.0
  flutter: 3.32.0

resolution: workspace

dependencies:
  core_common: any
  core_designsystem: any
  core_model: any
  flutter:
    sdk: flutter
  flutter_hooks: 0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.6.1
  freezed_annotation: 3.0.0
  intl: 0.20.2
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.15
  core_testing: any
  flutter_test:
    sdk: flutter
  freezed: 3.0.6
  riverpod_generator: 2.6.5
  yumemi_lints: 4.0.0

flutter:
