name: core_ui
description: This package provides a UI that depends on the model class and is used by all packages.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.0-180.3.beta
  flutter: 3.23.0-0.1.pre

dependencies:
  core_common:
    path: ../common
  core_designsystem:
    path: ../designsystem
  core_model:
    path: ../model
  flutter:
    sdk: flutter

dev_dependencies:
  core_testing:
    path: ../testing
  flutter_test:
    sdk: flutter
  yumemi_lints: 2.1.0

flutter:
