name: feature_quest
description: "This package provides quest features."
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.4.1
  flutter: 3.22.1

dependencies:
  core_common:
    path: ../../core/common
  core_designsystem:
    path: ../../core/designsystem
  core_domain:
    path: ../../core/domain
  core_model:
    path: ../../core/model
  core_ui:
    path: ../../core/ui
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1
  go_router: 14.1.3
  hooks_riverpod: 2.5.1
  riverpod_annotation: 2.3.5

dependency_overrides:
  # workaround
  # So, because feature_quest depends on both flutter_test from sdk and riverpod_generator 2.4.2, version solving failed.
  meta: 1.15.0

dev_dependencies:
  build_runner: 2.4.10
  core_testing:
    path: ../../core/testing
  flutter_test:
    sdk: flutter
  freezed: 2.5.3
  riverpod_generator: 2.4.2
  yumemi_lints: 1.7.0

flutter:
