name: feature_quest
description: "This package provides quest features."
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.0-180.3.beta
  flutter: 3.23.0-0.1.pre

dependencies:
  core_common:
    path: ../../core/common
  core_designsystem:
    path: ../../core/designsystem
  core_domain:
    path: ../../core/domain
  core_model:
    path: ../../core/model
  core_ui:
    path: ../../core/ui
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 2.4.2
  go_router: 14.2.0
  hooks_riverpod: 2.5.1
  intl: 0.19.0
  riverpod_annotation: 2.3.5

dependency_overrides:
  # workaround
  # So, because feature_quest depends on both flutter_test from sdk and riverpod_generator 2.4.2, version solving failed.
  meta: 1.15.0

dev_dependencies:
  build_runner: 2.4.11
  core_testing:
    path: ../../core/testing
  flutter_test:
    sdk: flutter
  freezed: 2.5.4
  riverpod_generator: 2.4.2
  yumemi_lints: 2.1.0

flutter:
