name: core_domain
description: This package provides use cases and domain models.
publish_to: "none"

environment:
  sdk: 3.5.3

dependencies:
  core_authenticator:
    path: ../authenticator
  core_common:
    path: ../common
  core_data:
    path: ../data
  core_model:
    path: ../model
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.13
  core_testing:
    path: ../testing
  riverpod_generator: 2.6.1
  test: 1.25.8
  yumemi_lints: 2.2.0
