name: core_domain
description: This package provides use cases and domain models.
publish_to: "none"

environment:
  sdk: 3.3.4

dependencies:
  core_common:
    path: ../common
  core_data:
    path: ../data
  core_model:
    path: ../model
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.9
  core_testing:
    path: ../testing
  riverpod_generator: 2.4.0
  test: 1.25.4
  yumemi_lints: 1.7.0
