name: core_domain
description: This package provides use cases and domain models.
publish_to: "none"

environment:
  sdk: 3.2.4
  flutter: 3.16.7

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: 1.3.0

flutter:
