name: feature_auth
description: "This package provides auth features."
publish_to: "none"

environment:
  sdk: 3.8.1
  flutter: 3.32.4

resolution: workspace

dependencies:
  core_common: any
  core_designsystem: any
  core_domain: any
  core_model: any
  core_ui: any
  flutter:
    sdk: flutter
  flutter_hooks: 0.21.2
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: 2.6.1
  intl: 0.20.2
  video_player: 2.9.5

dev_dependencies:
  core_testing: any
  flutter_test:
    sdk: flutter
  yumemi_lints: 4.0.0

flutter:
  assets:
    - assets/videos/
