name: 'Checks'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # https://github.com/kuhnroyal/flutter-fvm-config-action
      - name: Fetch flutter config
        uses: kuhnroyal/flutter-fvm-config-action@v2.0
        id: fvm-config-action

      # https://github.com/subosito/flutter-action
      - name: Setup flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      # https://github.com/marketplace/actions/melos-action
      - name: Melos action
        uses: bluefireteam/melos-action@v3

      - name: Run test
        run: melos run test --no-select
