name: Checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    uses: ./.github/workflows/wc-changes.yml

  action:
    runs-on: ubuntu-24.04
    needs: changes
    if: needs.changes.outputs.action == 'true'
    permissions:
      checks: "write"
      contents: "read"
      pull-requests: "write"
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/actionlint-with-reviewdog
      - uses: reviewdog/action-actionlint@db58217885f9a6570da9c71be4e40ec33fe44a1f # v1.65.0
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: error
          reporter: github-pr-review

  analyze:
    runs-on: ubuntu-24.04
    needs:
      - changes
    if: needs.changes.outputs.analyze == 'true'
    timeout-minutes: 10

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11

      - name: setup gitignore target files
        uses: ./.github/actions/setup-gitignore-target-files

      - name: setup pub
        uses: ./.github/actions/setup-pub

      - name: Run analyze
        run: melos analyze

  test:
    runs-on: ubuntu-24.04
    needs:
      - changes
    if: needs.changes.outputs.test == 'true'
    timeout-minutes: 10

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11

      - name: setup gitignore target files
        uses: ./.github/actions/setup-gitignore-target-files

      - name: setup pub
        uses: ./.github/actions/setup-pub

      - name: Setup very_good_cli
        run: dart pub global activate very_good_cli

      - name: Run test
        run: melos run ci:test --no-select

  semantic-pull-request:
    name: Semantic Pull Request
    runs-on: ubuntu-24.04
    needs:
      - changes
    if: needs.changes.outputs.semantic_pr == 'true'
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1.11.5
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      # https://github.com/marketplace/actions/semantic-pull-request
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

  status-check:
    runs-on: ubuntu-24.04
    needs:
      - analyze
      - test
      - action
      - semantic-pull-request
    permissions: { }
    if: failure()
    steps:
      - run: exit 1
