name: 'Checks'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: read
    outputs:
      action: ${{ steps.changes.outputs.action }}
      all: ${{ steps.changes.outputs.all }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: Paths Changes Filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            action:
              - '.github/workflows/*.yml'
            all:
              - '.github/workflows/checks.yml'
              - '.tool-versions'
              - 'melos.yaml'
              - 'app/**/*'
              - 'core/**/lib/**/*'
              - 'feature/**/lib/**/*'
              - '**/pubspec.lock'
              - '**/pubspec.yaml'

  cache-deps:
    runs-on: ubuntu-22.04
    needs: changed
    if: needs.changed.outputs.all == 'true'
    timeout-minutes: 10

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@0c39a522dfbced3ed83924152c45804a71ce216f # v2.0.4

      # https://github.com/marketplace/actions/cache
      - name: Cache pub-cache
        id: cache-pub-cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        env:
          cache-name: pub-cache
        with:
          # pub-cache files are stored in `~/.pub-cache` on Linux/macOS
          path: ~/.pub-cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      - name: Path pub-cache
        run: echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"

      - name: Setup Melos
        run: |
          dart pub global activate melos
          melos bootstrap

  analyze:
    runs-on: ubuntu-22.04
    needs:
      - changed
      - cache-deps
    if: needs.changed.outputs.all == 'true'
    timeout-minutes: 10

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@0c39a522dfbced3ed83924152c45804a71ce216f # v2.0.4

      # https://github.com/marketplace/actions/cache
      - name: Cache pub-cache
        id: cache-pub-cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        env:
          cache-name: pub-cache
        with:
          # pub-cache files are stored in `~/.pub-cache` on Linux/macOS
          path: ~/.pub-cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      - name: Path pub-cache
        run: echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"

      - name: Setup Melos
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: Run analyze
        run: melos run ci:analyze

  test:
    runs-on: ubuntu-22.04
    needs:
      - changed
      - cache-deps
    if: needs.changed.outputs.all == 'true'
    timeout-minutes: 10

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@0c39a522dfbced3ed83924152c45804a71ce216f # v2.0.4

      # https://github.com/marketplace/actions/cache
      - name: Cache pub-cache
        id: cache-pub-cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        env:
          cache-name: pub-cache
        with:
          # pub-cache files are stored in `~/.pub-cache` on Linux/macOS
          path: ~/.pub-cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      - name: Path pub-cache
        run: echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"

      - name: Setup Melos
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: Setup very_good_cli
        run: dart pub global activate very_good_cli

      - name: Run test
        run: melos run ci:test --no-select

  check-action:
    runs-on: ubuntu-22.04
    needs: changed
    if: needs.changed.outputs.action == 'true'
    permissions:
      checks: "write"
      contents: "read"
      pull-requests: "write"
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      # https://github.com/marketplace/actions/actionlint-with-reviewdog
      - uses: reviewdog/action-actionlint@9d8b58041eed1373f173e91b9a3db5a844197236 # v1.44.0
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: error
          reporter: github-pr-review

  status-check:
    runs-on: ubuntu-22.04
    needs:
      - analyze
      - test
      - check-action
    permissions: { }
    if: failure()
    steps:
      - run: exit 1
