name: 'Checks'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: read
    outputs:
      action: ${{ steps.changes.outputs.action }}
      all: ${{ steps.changes.outputs.all }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: Paths Changes Filter
        uses: dorny/paths-filter@ebc4d7e9ebcb0b1eb21480bb8f43113e996ac77a # v3.0.1
        id: changes
        with:
          filters: |
            action:
              - '.github/workflows/*.yml'
            all:
              - '.github/workflows/checks.yml'
              - '.tool-versions'
              - 'melos.yaml'
              - 'app/**/*'
              - 'core/**/lib/**/*'
              - 'feature/**/lib/**/*'
              - '**/pubspec.lock'
              - '**/pubspec.yaml'

  check:
    runs-on: ubuntu-22.04
    needs: changed
    if: needs.changed.outputs.all == 'true'
    timeout-minutes: 10

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@3bc85396a273ed82bba5e53a15174bbf9dba095c # v2.0.2

      - name: Path pub-cache
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Setup Melos
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: Run analyze
        run: melos run analyze

      - name: Run test
        run: melos run test --no-select

  check-action:
    runs-on: ubuntu-22.04
    needs: changed
    if: needs.changed.outputs.action == 'true'
    permissions:
      checks: "write"
      contents: "read"
      pull-requests: "write"
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # https://github.com/marketplace/actions/actionlint-with-reviewdog
      - uses: reviewdog/action-actionlint@6a38513dd4d2e818798c5c73d0870adbb82de4a4 # v1.41.0
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: error
          reporter: github-pr-review

  status-check:
    runs-on: ubuntu-22.04
    needs:
      - check
      - check-action
    permissions: { }
    if: failure()
    steps:
      - run: exit 1
