name: "Dependabot Auto Merge"

on:
  pull_request: ~

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-22.04
    if: github.actor == 'dependabot[bot]'
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1.9.2
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      # https://github.com/marketplace/actions/fetch-metadata-from-dependabot-prs
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.0.0
        with:
          github-token: "${{ steps.app-token.outputs.token }}"

      # https://github.com/marketplace/actions/github-action-merge-dependabot
      - name: Github Action Merge Dependabot
        uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          target: minor
