name: "Deploy to Firebase Hosting on PR"

on:
  pull_request:
    paths:
      - '.github/workflows/firebase-hosting-pull-request.yml'
      - '.tool-versions'
      - 'melos.yaml'
      - '**/*.dart'
      - '**/pubspec.*'

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-preview:
    uses: ./.github/workflows/wc-firebase-hosting.yml
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    with:
      gh-app-id: ${{ vars.BOT_APP_ID }}
      environment: 'development'
      project-id: 'asis-quest-dev'
    secrets:
      gh-app-private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      firebase-service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}
