name: "Deploy to Firebase Hosting on merge"

on:
  push:
    branches:
      - main

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    uses: ./.github/workflows/wc-firebase-hosting.yml
    permissions:
      contents: read
      deployments: write
    with:
      channel-id: 'live'
      environment: 'development' # TODO: change to staging
      gh-app-id: ${{ vars.BOT_APP_ID }}
      project-id: 'asis-quest-dev' # TODO: change to staging
    secrets:
      gh-app-private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      firebase-service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }} # TODO: change to staging
