name: "Deploy to Firebase Hosting on merge"

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/firebase-hosting-merge.yml'
      - '.tool-versions'
      - 'melos.yaml'
      - '**/*.dart'
      - '**/pubspec.*'

concurrency:
  group: staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    uses: ./.github/workflows/wc-firebase-hosting.yml
    permissions:
      contents: read
      deployments: write
    with:
      channel-id: 'live'
      environment: 'staging'
      gh-app-id: ${{ vars.BOT_APP_ID }}
      project-id: 'asis-quest-stg'
    secrets:
      gh-app-private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      firebase-service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STG }}
