name: "Check for changes in paths"

on:
  workflow_call:
    outputs:
      action:
        value: ${{ jobs.changes.outputs.action }}
      backend:
        value: ${{ jobs.changes.outputs.backend }}
      analyze:
        value: ${{ jobs.changes.outputs.analyze }}
      any:
        value: ${{ jobs.changes.outputs.any }}
      test:
        value: ${{ jobs.changes.outputs.test }}
      dependencies:
        value: ${{ jobs.changes.outputs.dependencies }}
      semantic_pr:
        value: ${{ jobs.pr_type.outputs.semantic_pr }}

permissions:
  contents: read
  pull-requests: read

jobs:
  pr_type:
    runs-on: ubuntu-24.04
    outputs:
      semantic_pr: ${{ steps.check.outputs.semantic_pr }}
    steps:
      - name: Check PR type
        id: check
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const eventType = context.eventName;
            const prAction = context.payload.action;

            const targetTypes = ['opened', 'edited', 'synchronize', 'reopened'];
            const shouldRun = eventType === 'pull_request_target' && targetTypes.includes(prAction);

            core.setOutput('semantic_pr', shouldRun);

  changes:
    runs-on: ubuntu-24.04
    outputs:
      action: ${{ steps.filter.outputs.action }}
      backend: ${{ steps.filter.outputs.backend }}
      analyze: ${{ steps.filter.outputs.analyze }}
      any: ${{ steps.filter.outputs.changes != '[]' }}
      test: ${{ steps.filter.outputs.test }}
      dependencies: ${{ steps.needs.outputs.dependencies }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: Paths Changes Filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            action:
              - '.github/actions/*.yml'
              - '.github/workflows/*.yml'
            backend:
              - 'app/backend/**/*'
              - 'core/network_model/**/*'
              - '.tool-versions'
              - '**/pubspec.*'
            analyze:
              - '.github/workflows/checks.yml'
              - '.github/workflows/wc-changed.yml'
              - '.tool-versions'
              - 'melos.yaml'
              - 'app/mobile/**/*'
              - 'core/**/lib/**/*'
              - 'feature/**/lib/**/*'
              - '**/pubspec.*'
            test:
              - '.github/workflows/checks.yml'
              - '.github/workflows/wc-changed.yml'
              - '.tool-versions'
              - 'melos.yaml'
              - 'app/mobile/**/*'
              - 'core/**/lib/**/*'
              - 'feature/**/lib/**/*'
              - '**/pubspec.*'

      - name: Check for dependencies changes
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: needs
        with:
          script: |
            const changes = ${{ steps.filter.outputs.changes }};

            // 依存関係の解決が必要な変更箇所
            const dependencies = [
              'analyze',
              'test',
            ];
            core.setOutput('dependencies', changes.some(value => dependencies.includes(value)));
