name: "Deploy to Firebase Hosting"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      gh-app-id:
        required: true
        type: string
      channel-id:
        required: false
        type: string
      project-id:
        required: true
        type: string
    secrets:
      gh-app-private-key:
        required: true
      firebase-service-account:
        required: true

jobs:
  build-and-deploy:
    environment: '${{ inputs.environment }}'
    runs-on: ubuntu-24.04-arm
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1

      - name: Generate gitignore target files
        run: make gen-gitignore-files

      - name: setup pub
        uses: ./.github/actions/setup-pub

      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        id: app-token
        with:
          app-id: ${{ inputs.gh-app-id }}
          private-key: ${{ secrets.gh-app-private-key }}

      # https://github.com/marketplace/actions/deploy-to-firebase-hosting
      - uses: FirebaseExtended/action-hosting-deploy@0cbcac4740c2bfb00d632f0b863b57713124eb5a # v0.9.0
        with:
          repoToken: '${{ steps.app-token.outputs.token }}'
          firebaseServiceAccount: '${{ secrets.firebase-service-account }}'
          channelId: '${{ inputs.channel-id }}'
          projectId: '${{ inputs.project-id }}'
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks