name: core_network_firestore
description: This package provides network operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.0-180.3.beta
  flutter: 3.23.0-0.1.pre

dependencies:
  cloud_firestore: 5.1.0
  core_authenticator:
    path: ../authenticator
  core_common:
    path: ../common
  core_model:
    path: ../model
  core_network:
    path: ../network
  flutter:
    sdk: flutter
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.11
  flutter_test:
    sdk: flutter
  riverpod_generator: 2.4.2
  yumemi_lints: 2.1.0
